name: Build

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-go@v5
      with:
        go-version: '1.24.2'

    - uses: extractions/setup-just@v2

    - name: Build project
      run: just build

    - name: Build Docker image
      run: just build-docker
